### ISSUE TITLE
Travis CI doesn't work

### ISSUE THREAD

**Issue by omkarnathsingh** [processone/xmpp#15]
As travis is not configured, remove it from Readme file also.

**Comment by zinid** [comment]
What's wrong with it? We have plans to add tests for Travis.

**Comment by omkarnathsingh** [comment]
Where is .travis configuration file? There are no results of CI for the project.

**Comment by zinid** [comment]
So? What's your problem?

**Comment by omkarnathsingh** [comment]
My problem is that, following lines should be removed from Readme file.

[![Build Status](https://travis-ci.org/processone/xmpp.svg?branch=master)](https://travis-ci.org/processone/xmpp) [![Coverage Status](https://coveralls.io/repos/processone/xmpp/badge.svg?branch=master&service=github)](https://coveralls.io/github/processone/xmpp?branch=master) [![Hex version](https://img.shields.io/hexpm/v/xmpp.svg "Hex version")](https://hex.pm/packages/xmpp)
