### ISSUE TITLE
How to use this project as a client?

### ISSUE THREAD

**Issue by omkarnathsingh** [processone/xmpp#24]
As https://github.com/processone/exmpp has been deprecated. How to use this project as a full Erlang client?

**Comment by zinid** [comment]
I don't think you can use the code for a client stuff. At least authentication is missing (only SASL EXTERNAL is supported, see [XEP-0178](https://xmpp.org/extensions/xep-0178.html))

**Comment by omkarnathsingh** [comment]
Okay. Basically my server is this one https://github.com/processone/ejabberd and I want to connect from multiple Eralng clients.

**Comment by zinid** [comment]
Well, you cannot do that without a lot of fiddling. It's on our TODO list to make `xmpp` library fully stand-alone.

**Comment by omkarnathsingh** [comment]
Okay @zinid . Thanks.
