### ISSUE TITLE
error while encoding #muc_subscription record

### ISSUE THREAD

**Issue by ltAldoRaine** [processone/xmpp#31]
I want to return extra attribute when user retrieves subscribed groups.

I added new column in muc_room_subscribers, and changed 

```
?SQL("select @(room)s from muc_room_subscribers where jid=%(JidS)s"
	     " and host=%(Host)s")
```
with this

```
?SQL("select @(room)s, @(unread)s from muc_room_subscribers where jid=%(JidS)s"
	     " and host=%(Host)s")
```

and 

`[jid:make(Room, Host, <<>>) || {Room} <- Subs];
`
with this

`[#muc_subscription{jid = jid:make(Room, Host, <<>>)), unread = binary_to_integer(Unread)} || {Room, Unread} <- Subs];
`
Also i changed xmpp_spec file and transfer new p1_mucsub.erl to ejabebrd deps/xmpp/src directory

i think i'm doing everything right, but when i retrieve subscribed groups i get this error.

![image](https://user-images.githubusercontent.com/17614392/40485193-f5621972-5f6e-11e8-9f20-29d00ac0a206.png)

**Comment by ltAldoRaine** [comment]
@zinid

**Comment by zinid** [comment]
wut?

**Comment by ltAldoRaine** [comment]
can you help me ?
