### ISSUE TITLE
Change presence unavailable status message

### ISSUE THREAD

**Issue by lovetox** [processone/xmpp#35]
```xml
<presence xmlns="jabber:client" to="user" from="chat@dino.im/xxx" type="unavailable">
  <x xmlns="http://jabber.org/protocol/muc#user">
    <item affiliation="none" role="none" />
  </x>
  <status xml:lang="en">Stream closed by us: Timed out waiting for stream resumption (connection-timeout)</status>
</presence>
```

status is a text that should be displayed by the client to the user receiving this presence, if my client displays to me "Stream closed by us:" i wonder, why did my client close the stream with that contact.

If the goal was to make clear which side did close a stream, the word "us" fails terribly in this setting.

**Comment by badlop** [comment]
Right, it's ambiguous... the destination user may wonder who is "us". What's your proposal?

**Comment by zinid** [comment]
> But mixing both user-set-status, and server-info-messages, seems not a good idea
> shortterm i just will not show any status on unavailable presences to the user anymore, to reach the goal to show only status which was set by the user.

I agree actually, that's the conclusion I came to as well after some thinking.
