### ISSUE TITLE
SCRAM-SHA-1-PLUS + SCRAM-SHA-256(-PLUS) supports

### ISSUE THREAD

**Issue by Neustradamus** [processone/xmpp#39]
"When using the SASL SCRAM mechanism, the SCRAM-SHA-256-PLUS variant SHOULD be preferred over the SCRAM-SHA-256 variant, and SHA-256 variants [RFC7677] SHOULD be preferred over SHA-1 variants [RFC5802]".

After SCRAM-SHA-1(-PLUS):
- https://tools.ietf.org/html/rfc5802
- https://tools.ietf.org/html/rfc6120

Now there is SCRAM-SHA-256(-PLUS):
- https://tools.ietf.org/html/rfc7677 since 2015-11-02
- https://tools.ietf.org/html/rfc8600 since 2019-06-21: https://mailarchive.ietf.org/arch/msg/ietf-announce/suJMmeMhuAOmGn_PJYgX5Vm8lNA

I add SCRAM-SHA-512(-PLUS): https://xmpp.org/extensions/inbox/hash-recommendations.html

Linked to:
- https://github.com/scram-xmpp/info/issues/1
- https://github.com/processone/ejabberd/issues/2742
- https://github.com/processone/ejabberd-contrib/issues/279

**Comment by zinid** [comment]
Stop it please.

**Comment by Neustradamus** [comment]
Thanks to @prefiks for SCRAM-SHA-1-PLUS + SCRAM-SHA-256(-PLUS) + SCRAM-SHA-512(-PLUS):
- https://github.com/processone/xmpp/commit/59b811f3814e09fe62bc1142bc9c6b6df8e9cd63
- https://github.com/processone/xmpp/commit/e21de94967c9d6b632058b1f5d34614e0dc9bfe8

**Comment by Neustradamus** [comment]
After previous commits:
- https://github.com/processone/xmpp/commit/59b811f3814e09fe62bc1142bc9c6b6df8e9cd63
- https://github.com/processone/xmpp/commit/e21de94967c9d6b632058b1f5d34614e0dc9bfe8

A new one:
- https://github.com/processone/xmpp/commit/651050f9619fd768491e8abb6e8db6c778eec2b3

**Comment by Neustradamus** [comment]
After previous commits:
- https://github.com/processone/xmpp/commit/59b811f3814e09fe62bc1142bc9c6b6df8e9cd63
- https://github.com/processone/xmpp/commit/e21de94967c9d6b632058b1f5d34614e0dc9bfe8
- https://github.com/processone/xmpp/commit/651050f9619fd768491e8abb6e8db6c778eec2b3

New commits about it:
- https://github.com/processone/xmpp/commit/70bad122a71efe519f6fa1c47cf63a75b450f4e1
- https://github.com/processone/xmpp/commit/0f61d2356323b98ad04739c6ce72a10061c19a7c
