### ISSUE TITLE
XEP-0009 ?

### ISSUE THREAD

**Issue by paradisaeidae** [processone/xmpp#41]
Hi Process-One,
I've been running ejabberd for some years now.
At one point I had xml-rpc enabled and usable.
With a ruby client.
Within a client stream (bosh), 5280 and suchlike.
I could nominate a call and send the stanza within.
Looks like this functionality has been moved to service ejabberd commands using the ejabberd_xmlrpc module?
Which is actived on a separate listener? (Understandable).
https://github.com/processone/xmpp shows no entry for XEP-0009.
I thought I might find a module in the contribs. Could not so far.
So my server is responding with 'No module to service this request'.
My frontend is js: Strophe.addNamespace("RPC", "jabber:iq:rpc")

Am I up for a refactoring week/month?

Thanks for ejabberd. Amaze.

**Comment by badlop** [comment]
> Looks like this functionality has been moved to service ejabberd commands using the ejabberd_xmlrpc module? Which is actived on a separate listener? (Understandable).

Right, the ejabberd module **mod_xmlrpc.erl** was converted into the ejabberd listener **ejabberd_xmlrpc.erl** several years ago.

See https://docs.ejabberd.im/admin/configuration/#listening-ports It's documented there and mentioned in an example configuration

**Comment by paradisaeidae** [comment]
This can also happen if the destination jabberID is ''.
Not sure if this is a critter.

**Comment by badlop** [comment]
ejabberd had mod_xmlrpc, and now [ejabberd_xmlrpc](http://localhost:8091/admin/configuration/listen/#ejabberd-xmlrpc) to accept XML-RPC requests, this is not related to [XEP-0009](https://xmpp.org/extensions/xep-0009.html).

From what I know, ejabberd has never supported XEP-0009. What version did you use to have that feature? Or what module did you install?

I cannot find any XMPP client or XMPP that supports XEP-0009 nowadays. The only reference I could find is the Prosody server: it added support for XEP-0009 in version 0.4.0 (year 2009), and removed that support in version 0.7.0 (year 2010).
