### ISSUE TITLE
Xmpp_idna was removed - breaks ejabberd builds using hex.pm

### ISSUE THREAD

**Issue by sarsonj** [processone/xmpp#42]
Hi,

we are using ejabberd in Elixir project - when 19.8.0 version is installed, the certificate loading is broken. The reason is missing xmpp_idna, that was removed from this project.

https://github.com/processone/xmpp/commit/f3517a9adaa4406c614e2234d3af10f1411196b9

IMHO changes like this should not be made when major version of lib didn't change as well...

```
20:31:04.354 [error] Hook ejabberd_started crashed when running ** (UndefinedFunctionError) function :xmpp_idna.domain_utf8_to_ascii/1 is undefined (module :xmpp_idna is not available)
    :xmpp_idna.domain_utf8_to_ascii("localhost")
    (ejabberd) src/ejabberd_pkix.erl:84: :ejabberd_pkix.get_certfile_no_default/1
    (ejabberd) src/ejabberd_pkix.erl:267: anonymous fn/1 in :ejabberd_pkix.check_domain_certfiles/1
    (stdlib) lists.erl:1338: :lists.foreach/2
    (ejabberd) src/ejabberd_pkix.erl:148: :ejabberd_pkix.handle_call/3
    (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3```

**Comment by zinid** [comment]
But xmpp-1.4.2 is not designed to work with 19.08, that's why ejabberd 19.09 is referencing to 1.4.2 in its rebar.config/mix.lock.

**Comment by sarsonj** [comment]
What I see in mix.exs in ejabberd 19.08:

`{:xmpp, "~> 1.4.0"}`

So that because of "~>" is used, not "==", it will use any newer version 1.4.x.

**Comment by zinid** [comment]
Well, I don't know how that Elixir stuff works, so maybe someone else would comment.

**Comment by sarsonj** [comment]
Thanks. As workaround I added to my app mix.exs more concrete dependency:

`{:xmpp, "== 1.4.0"}`

But generally speaking - I don't know, how it works in Erlang, but usually, in libs changes like from 1.4.0 to 1.4.1 don't break public API and are used for bugfixes. That is the reason for semantic versioning used in Elixir package manager and in other platforms too (I don't know if you have it in Erlang too). 

https://semver.org

**Comment by zinid** [comment]
That's not API breaking, that's the point. That usage of xmpp_idna in ejabberd was a dirty hack and it wasn't supposed to be used elsewhere, and ejabberd's rebar.config is properly tagged. So the only problem is mistagged Elixir stuff, but this has nothing to do with API breaking.

**Comment by sarsonj** [comment]
It is API breaking in context of elixir packages. In hex.pm package manager, there is ejabberd package and also xmpp package.

https://hex.pm/packages/ejabberd
https://hex.pm/packages/xmpp

Elabberd package is using xmpp package and ejabberd package 19.8.0 has semantic dependency to 1.4.x version. That xmpp_idna was called from sources, that are in Ejabberd package, not from xmpp package only.  I don't know, who maintains Elixir support in Ejabberd, but dependency to internal libs (like xmpp) should be concrete, so that without` "~>"` symbol.

**Comment by zinid** [comment]
Again, this should be fixed in ejabberd then. I will not rollback the changes or re-tag.

**Comment by prefiks** [comment]
Ah sorry i missed that this is breaking change, i only did check spec stuff that was backward compatible, if i would know that i would just bump major version...
