### ISSUE TITLE
RFCs and XEPs support page with VERSION

### ISSUE THREAD

**Issue by Neustradamus** [processone/xmpp#48]
On the README, it is possible to have a XEPs and RFCs support page with version (XEP-XXXX v1.2)?
- https://github.com/processone/xmpp/blob/master/README.md

Currently there are only XEP-XXXX, there are not version and not RFCs.

Examples:
- https://github.com/UWPX/UWPX-Client/blob/master/README.md
- https://github.com/telldus/xmppjs-client-plugins/blob/master/README.md
- https://github.com/ortuman/jackal/blob/master/README.md
- https://profanity-im.github.io/xeps.html
- https://metronome.im/supported-xeps-list
- https://dev.gajim.org/gajim/gajim/wikis/help/GajimXEPSupport
- https://github.com/jappix/jappix/blob/master/PROTOCOL.md

**Comment by badlop** [comment]
That information is already present in the xmpp.doap file, which is later visible in the xmpp.org website. Keeping duplicate  information requires additional work and prone to incoherences.

For now, let's keep the raw list of XEPs in README, and link to xmpp.org which shows additional details.

**Comment by Neustradamus** [comment]
@badlop: Yes I know about the xmpp.doap file but XEP versions are not in this file:
- https://github.com/processone/xmpp/blob/master/xmpp.doap

There are more here:
- https://github.com/processone/ejabberd/blob/master/ejabberd.doap

Note: There is a problem here for XEP-0398: 0.2.00.2.0

You can look to update XEP versions:
- https://xmpp.org/software/ejabberd/
- https://xmpp.org/software/erlang-elixir-xmpp/
