### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by noonessenpa1** [processone/xmpp#49]
i did what the manual said but only got this error messege:
root@DESKTOP-MHFT6P1:/home/senpa1/tidos-framework# cd xmpp
root@DESKTOP-MHFT6P1:/home/senpa1/tidos-framework/xmpp# ls
asn1          CODE_OF_CONDUCT.md  c_src  include      Makefile   rebar         rebar.config.script  src
CHANGELOG.md  CONTRIBUTING.md     doc    LICENSE.txt  README.md  rebar.config  specs
root@DESKTOP-MHFT6P1:/home/senpa1/tidos-framework/xmpp# make
./rebar get-deps compile
/usr/bin/env: ‘escript’: No such file or directory
make: *** [Makefile:7: src] Error 127
root@DESKTOP-MHFT6P1:/home/senpa1/tidos-framework/xmpp#                 

can you please help me

**Comment by prefiks** [comment]
Hello,

escript is part of erlang compiler, you need to have it installed (and accessible from PATH) to be able to compile this module.
