### ISSUE TITLE
How to add custom stanza

### ISSUE THREAD

**Issue by nOmi7** [processone/xmpp#6]
What version of ejabberd are you using?
    17.01.45

    What operating system (version) are you using?
    deb

    How did you install ejabberd (source, package, distribution)?
    source

new deps/xmpp project has spec file which then is used to generate the xmpp_codec.erl
%% Created automatically by XML generator (fxml_gen.erl)
%% Source: xmpp_codec.spec

We have few custom stanzas and i would like to include them for encoding and decoding.
for this

    I need any pointers on how to best write the spec for stanza in xmpp_codec.spec
    once written how and what to execute to generate the xmpp_codec.erl file.

there is no enough doc for https://github.com/processone/xmpp
Please help

Merci.

**Comment by zinid** [comment]
If your namespaces are registered by XSF, then make a PR and we will merge it.
Otherwise there is currently no way to add it except forking the repo. We're working on the solution for this.
Regarding the documentation: there is no documentation (yet?), at the moment you can find a stanza which is very close to yours and use its spec as an example.

**Comment by nOmi7** [comment]
Ok once I create spec how do I generate the erl file? 

Sent from Yahoo Mail on Android 
 
  On Fri, Jan 27, 2017 at 9:30 PM, Evgeny Khramtsov<notifications@github.com> wrote:   
If your namespaces are registered by XSF, then make a PR and we will merge it.
Otherwise there is currently no way to add it except forking the repo. We're working on the solution for this.
Regarding the documentation: there is no documentation (yet?), at the moment you can find a stanza which is very close to yours and use its spec as an example.

**Comment by zinid** [comment]
`make spec`

**Comment by nOmi7** [comment]
193-43:~/Documents/ejabberd/deps/xmpp on master]
% make spec
erl -noinput +B -pa ebin -pa deps/*/ebin -eval \
'case fxml_gen:compile("specs/xmpp_codec.spec", [{add_type_specs, xmpp_element}, {erl_dir, "src"}, {hrl_dir, "include"}]) of ok -> halt(0); _ -> halt(1) end.'
{"init terminating in do_boot",{undef,[{fxml_gen,compile,["specs/xmpp_codec.spec",[{add_type_specs,xmpp_element},{erl_dir,"src"},{hrl_dir,"include"}]],[]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,670}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,269}]},{init,start_it,1,[]},{init,start_em,1,[]}]}}
init terminating in do_boot ()
Makefile:10: recipe for target 'spec' failed
make: *** [spec] User defined signal 2

**Comment by nOmi7** [comment]
this error is without adding any of my changes .... tried to run as is first what wrong am i doing ?

**Comment by zinid** [comment]
compile first: `make`

**Comment by nOmi7** [comment]
ok update  i did pull deps for xmpp first later tried make spec @zinid 

so now I  get error 


 make spec 
erl -noinput +B -pa ebin -pa deps/*/ebin -eval \
'case fxml_gen:compile("specs/xmpp_codec.spec", [{add_type_specs, xmpp_element}, {erl_dir, "src"}, {hrl_dir, "include"}]) of ok -> halt(0); _ -> halt(1) end.'
failed to compile "specs/xmpp_codec.spec": {'EXIT',
                                            {{case_clause,{mod}},
                                             [{erl_types,t_from_form1,5,
                                               [{file,"erl_types.erl"},
                                                {line,4107}]},
                                              {erl_types,t_from_form,5,
                                               [{file,"erl_types.erl"},
                                                {line,4074}]},
                                              {fxml_gen,get_fun_return_type,
                                               3,
                                               [{file,"src/fxml_gen.erl"},
                                                {line,1776}]},
                                              {fxml_gen,prepare_default,4,
                                               [{file,"src/fxml_gen.erl"},
                                                {line,2057}]},
                                              {fxml_gen,prepare_attr,4,
                                               [{file,"src/fxml_gen.erl"},
                                                {line,2080}]},
                                              {lists,map,2,
                                               [{file,"lists.erl"},
                                                {line,1238}]},
                                              {fxml_gen,prepare_elem,5,
                                               [{file,"src/fxml_gen.erl"},
                                                {line,2019}]},
                                              {fxml_gen,'-compile/4-fun-3-',
                                               5,
                                               [{file,"src/fxml_gen.erl"},
                                                {line,210}]}]}}
Makefile:10: recipe for target 'spec' failed
make: *** [spec] Error 1

**Comment by nOmi7** [comment]
erl                                                                                                                      1 ↵
Erlang/OTP 18 [erts-7.3.1.2] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V7.3.1.2  (abort with ^G)

**Comment by zinid** [comment]
Is it possible to update to 19? I didn't test it with <19.

**Comment by nOmi7** [comment]
I tried to update it however my system doesn't have 19 rpm package yet can you please help me in testing it on below 19? Thanks @zinid

**Comment by zinid** [comment]
I fixed fxml_gen.erl so it now supports OTP18+. Please retry with the new version:
```
$ make clean
$ make
$ make spec
```

**Comment by nOmi7** [comment]
bingo it did work thanks for your attention I would try to add my spec and report incase of any problems @zinid

**Comment by zinid** [comment]
I'm reopening the issue to track the progress on external specifications support.

**Comment by zinid** [comment]
XMPP codec now supports submodules.
See #9 for details.

**Comment by loguntsov** [comment]
Hi. I didn't get actual way to add custom stanza. My answer in #9 is just simple way, and it is not recommend to  use. Because it change original sources in automatic mode, so is there another way to do this ?

Thanks.
