### ISSUE TITLE
How to decode with var

### ISSUE THREAD

**Issue by nOmi7** [processone/xmpp#7]
Hello i want to write a custom spec  in xmpp_codec.spec which will decode json cdata

_-xml(sync,
     #elem{name = <<"sync">>,
     xmlns =  <<"mycustom:xmlsns:sync">>,
     cdata =  #cdata{label = '$json',
     			  dec = {jsonutil,dec_json, []},  ### how to pass the attribute variable here 
     			  enc = {jsonutil,enc_json, []}},  ### how to pass the attribute variable here 
     result = {sync, '$c','$json', '$_els'},
     attrs = [ #attr{name = <<"c">>,
                     default = 0}
             ]})._

in dec = dec_json ,  [] i want to pass the label '$c' so that my decode will be based on '$c'

how can i achieve this right now it just accepts the atom or constants is it possible to pass a attribute var ?
any other method i can achieve this? 

Merci

**Comment by zinid** [comment]
Conditional decoding is unsupported. I was thinking about it, but it's not that simple and may introduce infinite loops.

**Comment by zinid** [comment]
Also, 'default = 0' is incorrect, you need to add dec/enc functions in this case.

**Comment by zinid** [comment]
It seems like you need something like this:
```erlang
-xml(sync,
     #elem{name = <<"sync">>,
           xmlns = <<"mycustom:xmlsns:sync">>,
           result = {sync, '$c','$json', '$_els'},
           cdata = #cdata{label = '$json'},
           attrs = [#attr{name = <<"c">>,
                          enc = {enc_int, []},
                          dec = {dec_int, [0, unlimited]},
                          default = 0}]}).
```
Then in ejabberd's code you should add json decoding/encoding of `#sync.json` based on `#sync.c` value.

**Comment by nOmi7** [comment]
yes zinid you are correct i need 
enc = {enc_int, []},
                          dec = {dec_int, [0, unlimited]},

however my json decoding should happen based on my attribute <<"c">>  is there any other way you could point me  to and i can try it

**Comment by zinid** [comment]
No, you should make decoding manually in the code, as I said above. E.g.
```erlang
foo(#sync{c = C, json = Data}) when C == 0 ->
    try jiffy:decode(Data) of
       JSON -> do_something(JSON)
    catch _:_ ->
          process_invalid_json()
    end;
...
```

**Comment by zinid** [comment]
I actually need this conditional decoding myself in some places (like privacy lists decoding), but implementing this is tough.

**Comment by nOmi7** [comment]
Cool thanks hope we can get this conditional decoding ... :) thanks for your help 👍
