### ISSUE TITLE
Implement XEP-0474: SASL SCRAM Downgrade Protection

### ISSUE THREAD

**Issue by tmolitor-stud-tu** [processone/xmpp#79]
The exact rationale and multiple examples why this specification fills an important gap in our XMPP security infrastructure is detailed in the XEP.

_The XEP is really simple, though, and should be easy to implement in ejabberd._

It is already implemented for prosody at https://modules.prosody.im/mod_sasl_ssdp.html

**Comment by prefiks** [comment]
Commit 01e41061e6adb8569ed595a2b0701a2b91db83b0 brings support for version 0.3.0 of that protocol.

**Comment by Neustradamus** [comment]
@prefiks: Now it supports all of this in more RFC9266?
- XEP-0388: Extensible SASL Profile: https://xmpp.org/extensions/xep-0388.html
- XEP-0440: SASL Channel-Binding Type Capability: https://xmpp.org/extensions/xep-0440.html
- XEP-0474: SASL SCRAM Downgrade Protection: https://xmpp.org/extensions/xep-0474.html

**Comment by tmolitor-stud-tu** [comment]
@prefiks Great, thanks!

**Comment by Neustradamus** [comment]
@badlop: Do not forget this XEP-0474 too ;)
