### ISSUE TITLE
Implement XEP-0480: SASL Upgrade Tasks

### ISSUE THREAD

**Issue by tmolitor-stud-tu** [processone/xmpp#80]
This is the last missing piece for modern SASL2 authentication: [XEP-0480: SASL Upgrade Tasks](https://xmpp.org/extensions/xep-0480.html) is needed to make sure clients can update the old SHA-1 password hashes to more secure alternatives like SHA-256.

This isn't as urgent as the other SASL2 related stuff you just implemented, but needed to make sure we can transition from SHA-1 to something more secure *before* SCRAM-SHA-1 becomes insecure.
This transition will take quite some time, so it is good to start early with this.

I promise this is the last SASL-related implementation request I'm doing ;)

BTW: This XEP was originally developed inside the main SASL2 XEP (XEP-0388) but later factored out to not create another of these large XEPs like MUC or PubSub.

**Comment by tmolitor-stud-tu** [comment]
Side note: I've wrote a blog post about modern SASL authentication that more or less lead to all of these XEPs over here: https://monal-im.org/post/00004-sasl/

**Comment by Neustradamus** [comment]
Important too :)

**Comment by Neustradamus** [comment]
@tmolitor-stud-tu: Good news, @prefiks has added the support in xmpp 1.9.0 and ejabberd 24.10, a big thanks!
- https://github.com/processone/xmpp/commit/85d4cb6c080f6328a174bdc12103fd65834a400b
- https://github.com/processone/ejabberd/commit/e9e678a994407cb52e0d4197006020041e87523f

**Comment by tmolitor-stud-tu** [comment]
Nice, thanks!!

**Comment by tmolitor-stud-tu** [comment]
@badlop I'm sorry, the xep had two errors, fixed over here: https://github.com/xsf/xeps/pull/1403
without base64 encoding, the salt could contain characters not allowed in xml and the schema didn't match the description and examples regarding the `iterations` attribute (it was still an element in the schema)

**Comment by tmolitor-stud-tu** [comment]
Example:
```
RECV(127): <task-data xmlns='urn:xmpp:sasl:2'><salt iterations='4096' xmlns='urn:xmpp:scram-upgrade:0'>êª0ﬂüb˚-h)√*!▒æ</salt></task-data>
XML parse error occurred: line: 1 , col: 1624 desc: The operation couldn’t be completed. (NSXMLParserErrorDomain error 9.)
```

**Comment by weiss** [comment]
[Fixed][1], thanks.

[1]: https://github.com/processone/xmpp/commit/f5551549e4ba7c27ba84ac4ba7ee7386644b816a

**Comment by Neustradamus** [comment]
@tmolitor-stud-tu, @weiss: Thanks for your reactivity!

**Comment by Neustradamus** [comment]
@badlop: Like you have seen, the @tmolitor-stud-tu XEP-0384 fix has been merged!

XEP-0384 0.2.0 is now official:
- https://xmpp.org/extensions/xep-0480.html

@weiss, @badlop: Thanks for your reactivity!
- https://github.com/processone/xmpp/commit/f5551549e4ba7c27ba84ac4ba7ee7386644b816a
- https://github.com/processone/xmpp/commit/3e883c3b52273a8ce31b3c458d2ecc180086df1b

@badlop: Oups, I have seen that it is not upstream, can you update too?
- https://github.com/badlop/ejabberd/commit/67aa9deed5c2eacfbdae33b154f5c02b4a501301

**Comment by Neustradamus** [comment]
@badlop: Like you have seen, the @tmolitor-stud-tu XEP-0480 fix has been merged!

XEP-0480 0.2.0 is now official:
- https://xmpp.org/extensions/xep-0480.html

@weiss, @badlop: Thanks for your reactivity!
- https://github.com/processone/xmpp/commit/f5551549e4ba7c27ba84ac4ba7ee7386644b816a
- https://github.com/processone/xmpp/commit/3e883c3b52273a8ce31b3c458d2ecc180086df1b

@badlop: Oups, I have seen that it is not upstream, can you update too?
- https://github.com/badlop/ejabberd/commit/67aa9deed5c2eacfbdae33b154f5c02b4a501301
