### ISSUE TITLE
XMPP codec should be modular

### ISSUE THREAD

**Issue by zinid** [processone/xmpp#9]
XMPP codec should allow third-party developers to create their own submodules and plug them into xmpp_codec.
This is implemented in 3976a85b40f85002713a93c74a0ffca664c3c062
Here is a brief description for developers about how they could use it:
* Clone xmpp library somewhere:
   `$ git clone https://github.com/processone/xmpp`
* Add new elements to `specs/xmpp_codec.spec` with proper `module` attribute set
* Recompile the codec:
   `$ make spec`
* The generator will create new file(s) in `src` directory. Those files are your submodules. Grab them to the working directory of your project.
* The generator also will generate new records (with specs) inside `include/xmpp_codec.hrl`. Grab those too in your project (either put them in your *.hrl files or in your *.erl files directly).
* In runtime, call to xmpp:register_codec/1 in order to register your submodule within xmpp_codec.

Done!
Not very clear, eh? OK, here is an example.

Let's say we want to add submodule for the following element:
```xml
<foo x='1' xmlns='ns:foo'/>
```
Clone the repo, open `specs/xmpp_codec.spec` and put the following spec somewhere inside it (the order doesn't matter):
```erlang
-xml(foo,
     #elem{name = <<"foo">>,
           xmlns = <<"ns:foo">>,
           module = foo,
           result = {foo, '$x'},
           attrs = [#attr{name = <<"x">>}]}).
```
Now type `make spec` in order to recompile the specification. New file will be created inside `src` directory:
```
$ git status
...
Untracked files:
   ...
   src/foo.erl
```
Copy this `foo.erl` into your working directory.
Now, consult the recompiled `xmpp_codec.hrl`:
```
$ git diff include/xmpp_codec.hrl
...
+-record(foo, {x = <<>> :: binary()}).
+-type foo() :: #foo{}.
+
...
```
Put this record and type definition somewhere in your files.
Now, you need to register your submodule (`foo`) during startup. This should look something like this:
```erlang
-module(mod_foo).
...
start(Blah, ...) ->
    ...
    xmpp:register_codec(foo),
    ...
```
Note, that you need to call `xmpp:register_codec/1` again, if you have your submodule (`foo`) recompiled and reloaded in runtime.
Also, you may want to unregister the submodule during shutdown procedure, although, strictly speaking, this is not required:
```erlang
stop(...) ->
    xmpp:unregister_codec(foo)
```
Now you have everything done to use your new "subcodec".
Have fun ;)

**Comment by nOmi7** [comment]
Great ... thanks will try it out soon

**Comment by nOmi7** [comment]
tag in rebar is 
{deps, [{fast_xml, ".*", {git, "https://github.com/processone/fast_xml", "23f60e2942113fcf5d87531c081ef47329c343ef"}  

should it be some version tag ? @zinid

**Comment by zinid** [comment]
No, we tag it during release, later.

**Comment by loguntsov** [comment]
This is example of script to build custom XMPP codec module for this library:

```
#!/bin/bash
rm -rf tmp
mkdir tmp
cd tmp
git clone https://github.com/processone/xmpp.git &&
cd xmpp &&
git checkout 1.1.9 &&
cat ../../specs/sec_history_xmpp.spec >> specs/xmpp_codec.spec &&
cp include/xmpp_codec.hrl include/xmpp_code_old.hrl &&
make all &&
make spec &&
cp src/sec_history_xmpp.erl ../../src/sec_history_xmpp.erl &&
echo -e "%% This file was generated automatically by compile_xmpp_spec.sh script\n\n" > ../../include/sec_xmpp_codec.hrl &&
diff -n include/xmpp_code_old.hrl include/xmpp_codec.hrl | grep -v "^\a" | grep -v "() |" >> ../../include/sec_xmpp_codec.hrl &&
cd ../..
rm -rf tmp

```

The project structure:
├── include
│   └── sec_xmpp_codec.hrl
├── Makefile
├── script
│   └── compile_xmpp_specs.sh
├── specs
│   └── sec_history_xmpp.spec
└── src
    └── sec_history_xmpp.erl

spec folder should contains specification additional tags.
script/compile_xmpp_specs.sh --- the script described above.
Script will generate 2 files:
./src/sec_history_xmpp -- source code for codec.
./include/sec_xmpp_codec.hrl --- header file with description of records and types.

Makefile can be like this:
```
.PHONY: spec
spec:
	script/compile_xmpp_specs.sh
```

So just run:
`make spec`
to build your own specification for xmpp.
After that you can use this module as:
`xmpp:register_codec(sec_history_xmpp.erl)`

**Comment by loguntsov** [comment]
By the way. All these flow are big crutches. XMPP library MUST allow build CUSTOM MODULES for all developers.

**Comment by zinid** [comment]
MORE CAPS

**Comment by ltAldoRaine** [comment]
how to make custom iq spec?  for example i have custom iq handler with query ns "NS-CUSTOM-MODULE"

**Comment by zinid** [comment]
@ltAldoRaine you can show an example of your IQ payload, so I can write some spec you can start with.

**Comment by ltAldoRaine** [comment]
<iq type=“get”><query xmlns=“jabber:iq:conversation”><start>0</start><limit>10</limit></query></iq> 

I did everything as you described. after restarting ejabberd there was error which was throwed by xmpp:register_codec()


7:47:40.261 [critical] Problem starting the module mod_conversation for host dev.mp.ge
 options: []
 error: undef
[{conversation,module_info,[md5],[]},
 {xmpp_codec,register_module,2,[{file,"src/xmpp_codec.erl"},{line,121}]},
 {mod_conversation,start,2,[{file,"src/mod_conversation.erl"},{line,42}]},
 {gen_mod,start_module,4,[{file,"src/gen_mod.erl"},{line,200}]},
 {lists,foreach,2,[{file,"lists.erl"},{line,1338}]},
 {gen_mod,start_link,0,[{file,"src/gen_mod.erl"},{line,79}]},
 {supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},
 {supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]}]
17:47:40.261 [critical] ejabberd initialization was aborted because a module start failed.
Problem starting the module mod_conversation for host dev.mp.ge
 options: []
 error: undef
[{conversation,module_info,[md5],[]},
 {xmpp_codec,register_module,2,[{file,"src/xmpp_codec.erl"},{line,121

Crash dump is being written to: /usr/local/var/log/ejabberd/erl_crash_20180205-174736.dump...done
[os_mon] memory supervisor port (memsup): Erlang has closed

**Comment by ltAldoRaine** [comment]
My custom iq is <iq type=“get”><query xmlns=“jabber:iq:conversation”><start>0</start><limit>10</limit></query></iq>

**Comment by zinid** [comment]
1. What Erlang version are you using?
2. Did you compile your spec so you get conversations.erl as an output?
3. Did you compile conversations.erl? Does Erlang see conversations.beam (use code:which/1 to check)?
4. Post your spec somewhere so I can check it correctness.

**Comment by ltAldoRaine** [comment]
1. Erlang/OTP 20 [erts-9.2]
2. yes it was generated in cloned xmpp src folder so i moved it to ejabberd deps/xmpp/src folder
3. i think i missed that part.. where should i compile in erlang ebin folder or ejabberd ebin folder

**Comment by zinid** [comment]
You should compile it inside your project. Then you just set `CONTRIB_MODULES_CONF_DIR` option in ejabberdctl.cfg which points to the beam files of your project.

**Comment by zinid** [comment]
You can of course compile it within ejabberd project (just put your ERL file inside `src` directory and run `make`).

**Comment by ltAldoRaine** [comment]
Thanks ! I will try second one..my module(not xmpp-codec) is also in ejabberd src folder

**Comment by rasel800** [comment]
I was experimenting with this example and still can't make it to work.
I am using ejabberd-18.12 in Mac, used OS X package to install ejabberd.

So the steps I have performed:
1. Clone XMPP and make
2. Added in specs/xmpp_codec.spec and make spec
-xml(foo,
     #elem{name = <<"foo">>,
           xmlns = <<"ns:foo">>,
           module = foo,
           result = {foo, '$x'},
           attrs = [#attr{name = <<"x">>}]}).
3. Compared the include/xmpp_codec.hrl before and after
4. Added the difference in foo.erl
-record(foo, {x = <<>> :: binary()}).
-type foo() :: #foo{}.
5. So foo.erl is like below, just for output to log:

-module(foo).
-include("logger.hrl").
-behaviour(gen_mod).
-record(foo, {x = <<>> :: binary()}).
-type foo() :: #foo{}.
start(Host, Opts) ->
    xmpp:register_codec(foo),
    gen_iq_handler:add_iq_handler(ejabberd_local, Host, <<"ns:foo">>, ?MODULE, process_local_iq),
    ok.
stop(Host) ->
    xmpp:unregister_codec(foo),
    gen_iq_handler:remove_iq_handler(ejabberd_local, Host, <<"ns:foo">>),
    ok.
process_local_iq(From, To, IQ) ->
    ?INFO_MSG("IQ received:~nFrom:~p~nTo:~p~nIQ:~p", [From, To, IQ]).

6. Compiled and loaded foo module by ejabberdctl module_upgrade foo
7. Sending XML:
<iq type="set" id="1234" to="localhost">
    <foo x='1' xmlns='ns:foo'/>
</iq>
8. Receiving XML:
<error code="503" type="cancel">
        <service-unavailable xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" />
        <text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" lang="en">No module is handling this query</text>
</error>

What am I missing here?
Do I need to replace the xmpp_codec.hrl and xmpp_codec.beam with the new compiled ones?

Would appreciate any suggestions please.

**Comment by zinid** [comment]
> What am I missing here?

The module `foo.erl` is generated automatically by the xmpp_codec, you can find it inside `src` directory of xmpp sources. You MUST NOT modify it. And your own module should have a different name, obviously, like mod_foo.erl.

**Comment by zinid** [comment]
> Compiled and loaded

What do you mean by "loaded"? Did you put it into ejabberd.yml?

**Comment by rasel800** [comment]
> > Compiled and loaded
> 
> What do you mean by "loaded"? Did you put it into ejabberd.yml?

No, I meant compiled and installed the module `mod_foo` using `ejabberdctl module_install mod_foo` command.
https://docs.ejabberd.im/admin/guide/managing/#ejabberdctl-commands

**Comment by zinid** [comment]
> Wondering why the ejabberdctl module_install mod_foo didn't get the module started in the first place?

Because a module typically requires some options.

**Comment by Zedonboy** [comment]
Hello, am using Elixir. Please i dont know how your @zinid example above, help people who compiled with elixir mix. Just point what i should do, i will find the rest for myself.

am using the latest 19.08
I use `iex -S mix` to start my server

**Comment by Zedonboy** [comment]
If you are still having this issue, check.. [here](https://stackoverflow.com/a/57640311/8587899)
